service: serverless-starter-app

frameworkVersion: ">=2.0.0"

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  timeout: 60
  stage: dev
  versionFunctions: false

functions:
  postcode:
    handler: handler.postcode
    events:
      - http:
          path: postcode/{postCode}
          method: get
          cors: true

plugins:
  - serverless-mocha-plugin
  - serverless-offline
  - serverless-webpack

custom:
  serverless-offline:
    port: 3001
    babelOptions:
      presets: ["env"]
  webpackIncludeModules:
    packagePath: './package.json'
